spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  http:
    encoding:
      enabled: false
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:seccyber
    password: pa
    username: sa

logging: 
    level.org.springframework:OFF
    level.root:OFF